# Generated by Django 3.2.12 on 2022-04-11 05:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PicoyplacaConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=100)),
                ('timezone', models.CharField(default='America/Guayaquil', max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PicoyplacaPause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('base_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configured_pauses', to='picoplacapredictor.picoyplacaconfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='PicoyplacaDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(help_text='ISO week day', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('plate_key', models.CharField(max_length=100)),
                ('base_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configured_days', to='picoplacapredictor.picoyplacaconfiguration')),
            ],
        ),
    ]
